#!/bin/bash

# # =========================== > Environment File < =========================== #
# # ┌┌────────────────────────────────────────────────────────────────────────┐┐ #
# # ││ This will check for an environment file and source it if it is there   ││ #
# # └└────────────────────────────────────────────────────────────────────────┘┘ #

CONTAINER_ENV_FILE=/.env

if [ -f ${CONTAINER_ENV_FILE} ]; then
    printf "%s" "sourcing $CONTAINER_ENV_FILE ... "
    source ${CONTAINER_ENV_FILE} && printf "%s\n" "ok" || printf "%s\n" "failed"
fi

# # ────────────────────────────────── <end> ─────────────────────────────────── #

# ============================ > Create folders < ============================ #
printf "%s" "creating $WORKDIR ... "
mkdir -p ${WORKDIR} && printf "%s\n" "ok" || printf "%s\n" "failed"

printf "%s" "creating $OUTDIR ... "
mkdir -p ${OUTDIR} && printf "%s\n" "ok" || printf "%s\n" "failed"
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ============= > Copy global .Rprofile and add path messages < ============== #

function copy_rprofile {
    # If .Rprofile does not exist in folder
    if [ ! -f ${1}/.Rprofile ]; then
        # # Copy /.Rprofile to folder
        # cp /.Rprofile ${1}/
        # # Change log message in .Rprofile to contain folder
        # sed -i 's|\(Loading\s*\).*\/\(.Rprofile\)|\1'"${1}"'\2|' ${1}/.Rprofile

        # Create symbolic link in folder
        ln -s /.Rprofile ${1}/.Rprofile 2>/dev/null || echo ""
    fi
}
printf "%s" "copying .Rprofile to $HOME ... "
copy_rprofile ${HOME}/ && printf "%s\n" "ok" || printf "%s\n" "failed"
printf "%s" "copying .Rprofile to $WORKDIR ... "
copy_rprofile ${WORKDIR} && printf "%s\n" "ok" || printf "%s\n" "failed"

# ────────────────────────────────── <end> ─────────────────────────────────── #

# ===================== > Enter projects input folder < ====================== #
printf "%s" "entering $WORKDIR ... "
cd ${WORKDIR} && printf "%s\n" "ok" || printf "%s\n" "failed"
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ========== > Execute the command(s) passed as arguments by user < ========== #
exec "$@"
# ────────────────────────────────── <end> ─────────────────────────────────── #
