stages:
  - build


build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - >-
      mkdir -p /kaniko/.docker;
      echo "{\"auths\":{\"${CI_REGISTRY}/containr\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 -w 0)\"}}}" > /kaniko/.docker/config.json;
      cd ${CI_PROJECT_DIR};
      export ubuntu_packages=$(cat requirements/Ubuntu);
      export r_packages=$(cat requirements/R);
    - >-
      /kaniko/executor
      --context "./"
      --dockerfile "./Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:sometag"
      --build-arg "ubuntu_packages"="${ubuntu_packages}"
      --build-arg "r_packages"="${r_packages}"
  # rules:
  #   - if: $CI_COMMIT_TAG