variables:
  r_version: rocker/r-ver:4.3.3

stages:
  - r-container-build

r-container-build:
  stage: r-container-build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - changes:
        paths:
          - dependencies/*
          - R/*
          - Dockerfile
          - .gitlab-ci.yml
          - containr_scripts/entrypoint
  script:
    - >-
      mkdir -p /kaniko/.docker;
      printf "{
          \"auths\": 
              {
                  \"${CI_REGISTRY}\": { 
                      \"auth\": \"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 -w 0)\"
                  }
              }
      }" \
      > /kaniko/.docker/config.json
    - >-
      cd ${CI_PROJECT_DIR};
      export ubuntu_packages=$(cat dependencies/Ubuntu);
      export r_packages=$(cat dependencies/R)
    - >-
      /kaniko/executor
      --context "./"
      --dockerfile "./Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/$(echo ${r_version} | sed 's/.*\///' | sed 's/\:.*//'):latest"
      --destination "${CI_REGISTRY_IMAGE}/$(echo ${r_version} | sed 's/.*\///')"
      --build-arg "r_version"="${r_version}"
      --build-arg "ubuntu_packages"="${ubuntu_packages}"
      --build-arg "r_packages"="${r_packages}"
      --build-arg "workdir"="/${CI_PROJECT_TITLE}/"
      --build-arg "outdir"="/${CI_PROJECT_TITLE}_output/"