variables:
  r_version: rocker/r-ver:4.3.3

stages:
  - r-container-build

r-container-build:
  stage: r-container-build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - changes:
        paths:
          - dependencies/*
          - R/*
          - Dockerfile
          - .gitlab-ci.yml
          - containr_scripts/entrypoint
  script:
    # Set folders
    - cd "${CI_PROJECT_DIR}" && mkdir -p /kaniko/.docker;
    # Set Credentials
    - >-
      printf "{
        \"auths\": 
        {
        \"${CI_REGISTRY}\":
          { 
            \"auth\": 
              \"$(
              printf "%s:%s" \
                "${CI_REGISTRY_USER}" \
                "${CI_REGISTRY_PASSWORD}" | \
              base64 -w 0
              )\"
          },
          \"index.docker.io\":
          { 
            \"auth\": 
              \"$(
              printf "%s:%s" \
                "silena" \
                "dckr_pat_OcPs0Yv044oquOa1ADz0O608lq4" | \
              base64 -w 0
              )\"
          }
        }
      }" \
      > /kaniko/.docker/config.json;
    - cat /kaniko/.docker/config.json;
    # Export package lists
    - >- 
      export ubuntu_packages=$(cat dependencies/Ubuntu 2>/dev/null || return 0);
      export r_packages=$(cat dependencies/R 2>/dev/null || return 0);
    # Build the container
    - >-
      /kaniko/executor
      --context "./"
      --dockerfile "./Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/$(echo ${r_version} | sed 's/.*\///' | sed 's/\:.*//'):latest"
      --destination "${CI_REGISTRY_IMAGE}/$(echo ${r_version} | sed 's/.*\///')"
      --destination "silena/containr:$(echo ${r_version} | sed 's/.*\///')"
      --build-arg "r_version"="${r_version}"
      --build-arg "ubuntu_packages"="${ubuntu_packages}"
      --build-arg "r_packages"="${r_packages}"
      --build-arg "workdir"="/${CI_PROJECT_TITLE}/"
      --build-arg "outdir"="/${CI_PROJECT_TITLE}_output/"