stages:
  - build


build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - >-
      mkdir -p /kaniko/.docker;
      echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "Blabla" "glpat-mf6XzgTC1o-fPPwx8VH3" | base64 -w 0)\"}}}" > /kaniko/.docker/config.json;
      cd ${CI_PROJECT_DIR};
      export ubuntu_packages=$(cat ./ubuntu_packages);
      export r_packages=$(cat ./r_packages);
    - >-
      /kaniko/executor
      --context "./docker_container"
      --dockerfile "./docker_container/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:BLA"
      --build-arg "ubuntu_packages"="${ubuntu_packages}"
      --build-arg "r_packages"="${r_packages}"
  # rules:
  #   - if: $CI_COMMIT_TAG
