variables:
  r_version: rocker/r-ver:latest

stages:
  - build

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - >-
      mkdir -p /kaniko/.docker;
      printf "{
          \"auths\": 
              {
                  \"${CI_REGISTRY}\": { 
                      \"auth\": \"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 -w 0)\"
                  }
              }
      }" \
      > /kaniko/.docker/config.json
    - >-
      cd ${CI_PROJECT_DIR};
      export ubuntu_packages=$(cat requirements/Ubuntu);
      export r_packages=$(cat requirements/R)
    - >-
      /kaniko/executor
      --context "./"
      --dockerfile "./Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/$(echo ${r_version} | sed 's/.*\///')"
      --build-arg "r_version"="${r_version}"
      --build-arg "ubuntu_packages"="${ubuntu_packages}"
      --build-arg "r_packages"="${r_packages}"