stages:
  - build


build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - >-
      mkdir -p /kaniko/.docker;
      echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 -w 0)\"}}}" > /kaniko/.docker/config.json;
      cd ${CI_PROJECT_DIR};
      echo "----------------------------------------------------------------------";
      echo "CI_REGISTRY: ${CI_REGISTRY}";
      echo "CI_REGISTRY_USER: ${CI_REGISTRY_USER}";
      echo "CI_REGISTRY_PASSWORD: ${CI_REGISTRY_PASSWORD}";
      echo "CI_PROJECT_DIR: ${CI_PROJECT_DIR}";
      echo "CI_REGISTRY_IMAGE: ${CI_REGISTRY_IMAGE}";
      echo "----------------------------------------------------------------------";
    - >-
      /kaniko/executor
      --context "./docker_container"
      --dockerfile "./docker_container/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:kaniko"
      --build-arg "ubuntu_packages"="${ubuntu_packages}"
      --build-arg "r_packages"="${r_packages}"
      --skip-push-permission-check
  # rules:
  #   - if: $CI_COMMIT_TAG
      # export ubuntu_packages=$(cat ./ubuntu_packages);
      # export r_packages=$(cat ./r_packages);