stages:
  - build


build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - export FILE_CONTENTS=$(cat ubuntu_packages)
    - echo "File contents: $FILE_CONTENTS"
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 -w 0)\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/docker_container"
      --dockerfile "${CI_PROJECT_DIR}/docker_container/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:BLA"
  # rules:
  #   - if: $CI_COMMIT_TAG
