#!/usr/bin/env bash

if [ -n "${__entrypoint_run__}" ]; then exit 0; fi
export __entrypoint_run__=true



# =========================== > Environment File < =========================== #
# ┌┌────────────────────────────────────────────────────────────────────────┐┐ #
# ││ This will check for an environment file and source it if it is there   ││ #
# └└────────────────────────────────────────────────────────────────────────┘┘ #

if [ -f ${HOME}/.env ]; then
    source "${HOME}/.env" || printf "%s\n" "source${HOME}/.env failed"
elif [ -f /.env ]; then
    source /.env || printf "%s\n" "source ${HOME}/.env failed"
fi

# ────────────────────────────────── <end> ─────────────────────────────────── #

# ============================ > Create folders < ============================ #
mkdir -p ${WORKDIR}  || printf "%s\n" "mkdir -p ${WORKDIR}  failed"
mkdir -p ${OUTDIR}  || printf "%s\n" "mkdir -p ${OUTDIR} failed"
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ============= > Copy global .Rprofile and add path messages < ============== #

function copy_rprofile {
    # If .Rprofile does not exist in folder
    if [ ! -f ${1}/.Rprofile ]; then
        # # Copy /.Rprofile to folder
        # cp /.Rprofile ${1}/
        # # Change log message in .Rprofile to contain folder
        # sed -i 's|\(Loading\s*\).*\/\(.Rprofile\)|\1'"${1}"'\2|' ${1}/.Rprofile

        # Create symbolic link in folder
        ln -s /.Rprofile ${1}/.Rprofile 2>/dev/null || echo ""
    fi
}
copy_rprofile ${HOME}/ || printf "%s\n" "Creating ${HOME}/.Rprofile failed"
copy_rprofile ${WORKDIR}/ || printf "%s\n" "Creating ${WORKDIR}/.Rprofile failed"

# ────────────────────────────────── <end> ─────────────────────────────────── #

# ================ > Link folders to user's home directory < ================= #
if [[ ! -d ${HOME}/$(basename $WORKDIR)/ ]]; then
    ln -s $WORKDIR/ ${HOME}/$(basename $WORKDIR)
fi
if [[ ! -d ${HOME}/$(basename $OUTDIR)/ ]]; then
    ln -s $OUTDIR/ ${HOME}/$(basename $OUTDIR)
fi
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ===================== > Enter projects input folder < ====================== #
cd ${HOME}/$(basename $WORKDIR) || printf "%s\n" "cd ${HOME}/$(basename $WORKDIR) failed"
# ────────────────────────────────── <end> ─────────────────────────────────── #

exec "$@"
